### ISSUE TITLE
Usage for esp8266 wires and questions b baseline

### ISSUE THREAD

**Issue by hanscees** [RobTillaart/SGP30#10]
Hi,
I was recommended this library for an issue here 
https://forum.arduino.cc/t/using-sgp30-lib-but-want-other-wires-how-esp8266/1077502

Is there a sketch you have that includes running both normal operation and includes using calibration as the arduino sketches have?
Your baseline sketch in examples does get a baseline but doesn't seem to write one, so that's mysterious. Perhaps writing it is somewhere else? 

Secondly can I use sgp.begin(5,4) to use these wires on esp8266 as sda and scl?

**Comment by RobTillaart** [comment]
Long since I actually worked with the library..

I do not recall calibrating the sensor otherwise I would have added it in the examples. For CO2 sensors the typical calibration is to have it outside for 20 minutes or an hour (check datasheet) as that is typical 400 ppm.
Calibrating TVOH don't know from my head. So the datasheet is first place to check. 
Second place could be adafruit website as they often have extended tutorials

**Comment by RobTillaart** [comment]
As far as I know esp8266 you can assign any pair to be used. See in this tutorial

https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/using-the-arduino-addon

**Comment by RobTillaart** [comment]
@hanscees 
Any progress to report?

**Comment by RobTillaart** [comment]
As there is no answer I assume the issue is solved.

**Comment by hanscees** [comment]
> @hanscees Any progress to report?

Sorry, I solved this by hardware, meaning I crosswired connections. So I didnt test, sorry.
thanks for the answers though!

**Comment by RobTillaart** [comment]
Ok, you're welcome
